spring:
  application:
    name: imobiliaria-api
  cassandra:
    local-datacenter: datacenter1
    contact-points: 192.168.100.27
    port: 9042
    keyspace-name: myKeyspace
    schema-action: CREATE_IF_NOT_EXISTS
  cache:
    type: redis
  data:
    redis:
      host: 192.168.100.27
      port: 6379
      serializer: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
server:
  port: 8080